# Generated by Django 5.1.2 on 2024-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_licence_number_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
