# Generated by Django 5.1.2 on 2024-10-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_driver_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
